city = "indianapolis"
cityAsList = list(city)
vowels = "aeiou"
consonants = "bcdfghjklmnpqrstvwxyz"

answerDict= { }
answerDict[1]= "indianapolis"
answerDict[2]= "indian"
answerDict[3]= "indian"
answerDict[4]= "n"
answerDict[5]= "indian" 
answerDict[6]= "Who controls the past, controls the future."
answerDict[7]= "Who controls the present, controls the past."
answerDict[8]= "Who controls the past, controls the future. Who controls the past, controls the future."
answerDict[9]= "Who controls the past, controls the future. Who controls the past, controls the future."
answerDict[10] = "0"
answerDict[11] = "1"
answerDict[12] = "1"
answerDict[13] = "12"
answerDict[14] = "i +=1"
answerDict[15] = " i=0"
answerDict[16]=  "condition"
answerDict[17]= "12"
answerDict[18]= "12"
answerDict[19]= "24"
answerDict[20]= "0"
answerDict[21]= "0"
answerDict[22]= "6"
answerDict[23]= "6"
answerDict[24]= "6"
answerDict[25]= "6"
answerDict[26]= "6"
answerDict[27]= "i=12, j=6"
answerDict[28]= "i=12, j=0"
answerDict[29]= "i=24, j=0"
answerDict[30]= "i=12, j=0"
answerDict[31]= "j=0, i=12"
answerDict[32]= "i=12, j=0"
answerDict[33]= "j=12, k=144, i=12"
answerDict[34]= "a=72, i=12, j= 12, k=144"

print(answerDict)
